### PR TITLE
Update start_sagemaker.md

### LINKED ISSUE #27: Amazon Sagemaker Instructions require updating
The Amazon Sagemaker instructions here:
https://course.fast.ai/start_sagemaker

Have gotten a bit stale and needed updated, specifically with a different cloudformation template.  Some of the issues users are reporting can be reviewed in this forum thread here:
https://forums.fast.ai/t/platform-amazon-sagemaker-aws/66020/29

PR to follow.

### PR DESCRIPTION
**Pull request by ezeeetm**
fixes #27

### CODE REVIEW

**Comment by jph00** [comment]
Many thanks.

**Comment by PO20** [comment]
Greetings, ezeeetm and Jeremy! ))

I faced issues with the current FastaiSageMakerStack cloudformation template and wound up modifying it as documented here: https://github.com/fastai/course20/issues/60. My FastaiSageMakerStack has been running without failure since the then.

This PR is the latest relevant update I have managed to find re this template. Since other people apparently continue facing the same issue (broken conda env), it would be great if you confirm the fix if you find it valid and point me in the direction to updating the cloud formation template (https://fastai-cfn.s3.amazonaws.com/sagemaker-cfn-course-v4.yml) so it works for the new entrants joining the course on AWS SageMaker.

Thank you!

Best
PO

**Comment by jph00** [comment]
Many thanks @PO20 . We don't have access to that template - it was created by AWS. I'll ask them to take a look.

**Comment by PO20** [comment]
@jph00: Thank you, Jeremy! This is greatly appreciated! Please let me know if I can help in any way.

Best
Peter

**Comment by mattmcclean** [comment]
The original template link has been fixed here - https://s3-eu-west-1.amazonaws.com/mmcclean-public-files/sagemaker-fastai-notebook/sagemaker-cfn-course-v4.yaml. However I don't have access to the S3 bucket named **fastai-cfn** which is the current template referred to in the _start_sagemaker_ page. @ezeeetm I believe owns this bucket so either he can update the template or I can submit a PR to revert back to the original URL

**Comment by PO20** [comment]
@mattmcclean : Many thanks, Matt! I understand that @ezeeetm is holding the keys to the FastaiSageMakerStack template home and we are now waiting for him to respond. Hopefully, we can clear the issue soon for the new entrants to enjoy convenience of AWS service for starting in the world of fastai.

Thank you!

Best
Peter

**Comment by jph00** [comment]
I'll update the docs to point at the working script

**Comment by PO20** [comment]
@jph00: Thank you, Jeremy! I confirm that the script posted by @mattmcclean contains the proposed fixes via these changes (pending your pointing):

added line 76:
```
	conda update --force-reinstall conda -y
```
removed lines 160, 161:
```
	echo "Updating conda"
                  
	conda update -n base -c defaults conda -y
```

.yaml vs .yml script extention differenced assumed to make no difference. 

Thank you!

**Comment by jph00** [comment]
Thanks all, I've updated the docs to point at @mattmcclean's script now.

**Comment by PO20** [comment]
@jph00 and @mattmcclean, thank you both for seeing this through by making the AWS stack script change and pointing the AWS CloudFormation links to the working templates! Go fastai + AWS ))!

Best
PO

**Pull request merged**
