### PR TITLE
Getting started with JarvisCloud

### PR DESCRIPTION
**Pull request by svishnu88**

### CODE REVIEW

**Comment by jph00** [comment]
Thanks @svishnu88 this is on the right track.

Remember that this is fast.ai docs - it's not appearing on your own site. So remove all use of the word "we", and remove all marketing-oriented comments (e.g. why JarvisCloud was created). Also, move all the stuff about how to manage your subscription to docs on your own site, and instead simply link to them. This PR should only tell people how to use the fast.ai book and course on JarvisCloud, and explain the pricing (especially, how to stop the instance so charging stops, and what charges occur when it's paused).

**Comment by svishnu88** [comment]
Ok @jph00. I will update the docs.

**Comment by svishnu88** [comment]
@jph00 I have updated the guide based on your feedback. Please let me know if further changes are needed.

**Comment by jph00** [comment]
Good job!

**Pull request merged**
