### PR TITLE
Google Cloud setup docs init

### PR DESCRIPTION
**Pull request by mistn**
Added init docs for google cloud setup using simplified notebooks creation method.

### CODE REVIEW

**Comment by jph00** [comment]
Thanks this is great

**Comment by jwuphysics** [comment]
I think the URL for requesting a quota increase may be incorrect. Since the updated version uses GCP AI Platform rather than GCP Compute Engine, the website needs to be updated from https://cloud.google.com/docs/quota#requesting_higher_quota to  https://cloud.google.com/ai-platform/training/docs/quotas#requesting_a_quota_increase

**Comment by jph00** [comment]
OK will fix. BTW @jwuphysics I don't normally see messages posted to closed issues - best to create a new issue and/or at-mention me. Or better still send in a PR! :)

**Comment by micstn** [comment]
> I think the URL for requesting a quota increase may be incorrect. Since the updated version uses GCP AI Platform rather than GCP Compute Engine, the website needs to be updated from https://cloud.google.com/docs/quota#requesting_higher_quota to https://cloud.google.com/ai-platform/training/docs/quotas#requesting_a_quota_increase

@jwuphysics the AI Platform uses normal Compute Engine VMs, i guess their documentation is not updated (June), the API Manager link you shared redirects now to Admin Quotas Page as it was in the docs. I will review the flow later this week but it should stay as was.

**Comment by jwuphysics** [comment]
@jph00 Thanks for the heads up, I'll do that next time!

@micstn Appreciate the details, that makes sense. For me, the page is correctly redirected, because I was "grandfathered in" with an existing GCP Compute Engine VM. But I'm helping somebody else set this up, and they are unable to find a way to request a quota increase. I will be working and trying to figure out what's going wrong (and if needed, will open a new issue/PR).

**Pull request merged**
